version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    logging:
      driver: none
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: mongo
